version: "3.3"
services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
      - 3000:3000
      - 8000:8000
    volumes:
      - ${LOCAL_DIR:-./html}:/var/www/html
      - ./log:/var/log/apache2
      - ./docker/laravel/config:/etc/apache2/sites-available
    working_dir: /var/www/html
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_USER=${DB_USER:-laravel}
      - MYSQL_PASSWORD=${DB_PASS:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=20480K
      - PMA_USER=${DB_USER:-laravel}
      - PMA_PASSWORD=${DB_PASS:-laravel}
    ports:
      - 8080:80

